# -- Main Navigation Menu --

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

# -- Footer Menu --

[[footer]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 20
